config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create, :edit] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  CATEGORY = %w[chinese italian japanese french belgian]

  validates :name, presence: true, exclusion: { in: [""] }
  validates :address, presence: true, exclusion: { in: [""] }
  # validates :phone_number, format: { with: /\A[a-zA-Z]+\z/,
  validates :category, presence: true, inclusion: { in: CATEGORY }

  def self.getCategories
    CATEGORY
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
  # presence: true, inclusion: { in: (1..5).to_a }
  # inclusion: { in: [0,1,2,3], allow_nil: false }
  validates :content, presence: true, exclusion: { in: [""] }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :get_instance_from_id, only: [:show, :edit]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @new_review = Review.new
    @reviews = Review.where(:restaurant_id == @restaurant.id)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(required_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  private

  def get_instance_from_id
    @restaurant = Restaurant.find(params[:id])
  end

  def required_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :get_instance_from_id, only: [:show, :edit]

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(required_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def get_instance_from_id
    @review = Review.find(params[:id])
  end

  def required_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurants list</h1>
  <%= link_to "Create a Restaurant", new_restaurant_path %>
  <% @restaurants.each do |r|  %>
  <div class="card m-1">
      <h2><%= r.name %>
      <%= link_to restaurant_path(r) do %>
        <i class="fas fa-search"></i>
      <% end %>
      </h2>
      <p>City: <%= r.address %></p>
      <p>Phone: <%= r.phone_number %></p>
      <p>Category: <%= r.category %></p>
  </div>
    <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
<h1>Create a Restaurant</h1>
  <%= simple_form_for @restaurant do |r| %>
    <%= r.input :name %>
    <%= r.input :address %>
    <%= r.input :phone_number %>
    <%= r.input :category, collection: Restaurant.getCategories %>
    <%= r.button :submit, class: "btn btn-primary" %>
  <% end %>
  <%= link_to "Back", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1><%= @restaurant.name %></h1>
  <p>City: <%= @restaurant.address %></p>
  <p>Phone: <%= @restaurant.phone_number %></p>
  <p>Category: <%= @restaurant.category %></p>
  <h2>Reviews :</h2>

  <%# <%= link_to"Create a Review", new_restaurant_review_path(@restaurant) %>
  <%= render "reviews/new", restaurant: @restaurant, review: @new_review %>

  <% @reviews.reverse.each do |r| %>
    <div class="card m-1">
      <div class="stars d-flex">
        <% r.rating.times do %>
          <i class="fas fa-star"></i>
        <% end %>
        <% (5 - r.rating).times do %>
          <i class="far fa-star"></i>
        <% end %>
      </div>
      <p><%= r.content %></p>
    </div>
  <% end %>
<%= link_to "Back", restaurants_path %>
</div>

app/views/reviews/_new.html.erb
<div class="container border m-1">
<h2>Create a Review</h2>
  <%= simple_form_for [ restaurant, review ] do |r| %>
    <%= r.input :rating, input_html: { min: '0' , max:'5'} %>
    <%= r.input :content %>
    <%= r.button :submit, class: "btn btn-primary" %>
  <% end %>
  <%# <%= link_to "Back", restaurant_reviews_path(restaurant) %>
</div>

app/views/reviews/new.html.erb
<div class="container">
<h1>Create a Review</h1>
  <%= simple_form_for [ @restaurant, @review ] do |r| %>
    <%= r.input :rating %>
    <%= r.input :content %>
    <%= r.button :submit, class: "btn btn-primary" %>
  <% end %>
  <%= link_to "Back", restaurant_reviews_path(@restaurant) %>
</div>